// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: pathInfo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NavV3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *NavV3) Reset() {
	*x = NavV3{}
	mi := &file_pathInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavV3) ProtoMessage() {}

func (x *NavV3) ProtoReflect() protoreflect.Message {
	mi := &file_pathInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavV3.ProtoReflect.Descriptor instead.
func (*NavV3) Descriptor() ([]byte, []int) {
	return file_pathInfo_proto_rawDescGZIP(), []int{0}
}

func (x *NavV3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NavV3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NavV3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type PathTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths []*NavV3 `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *PathTest) Reset() {
	*x = PathTest{}
	mi := &file_pathInfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathTest) ProtoMessage() {}

func (x *PathTest) ProtoReflect() protoreflect.Message {
	mi := &file_pathInfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathTest.ProtoReflect.Descriptor instead.
func (*PathTest) Descriptor() ([]byte, []int) {
	return file_pathInfo_proto_rawDescGZIP(), []int{1}
}

func (x *PathTest) GetPaths() []*NavV3 {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_pathInfo_proto protoreflect.FileDescriptor

var file_pathInfo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x61, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x61, 0x74, 0x68, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x31, 0x0a, 0x05, 0x4e, 0x61,
	0x76, 0x56, 0x33, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12,
	0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x31, 0x0a,
	0x08, 0x50, 0x61, 0x74, 0x68, 0x54, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x70, 0x61, 0x74,
	0x68, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x4e, 0x61, 0x76, 0x56, 0x33, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73,
	0x42, 0x12, 0x5a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pathInfo_proto_rawDescOnce sync.Once
	file_pathInfo_proto_rawDescData = file_pathInfo_proto_rawDesc
)

func file_pathInfo_proto_rawDescGZIP() []byte {
	file_pathInfo_proto_rawDescOnce.Do(func() {
		file_pathInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_pathInfo_proto_rawDescData)
	})
	return file_pathInfo_proto_rawDescData
}

var file_pathInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pathInfo_proto_goTypes = []any{
	(*NavV3)(nil),    // 0: pathinfo.NavV3
	(*PathTest)(nil), // 1: pathinfo.PathTest
}
var file_pathInfo_proto_depIdxs = []int32{
	0, // 0: pathinfo.PathTest.paths:type_name -> pathinfo.NavV3
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pathInfo_proto_init() }
func file_pathInfo_proto_init() {
	if File_pathInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pathInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pathInfo_proto_goTypes,
		DependencyIndexes: file_pathInfo_proto_depIdxs,
		MessageInfos:      file_pathInfo_proto_msgTypes,
	}.Build()
	File_pathInfo_proto = out.File
	file_pathInfo_proto_rawDesc = nil
	file_pathInfo_proto_goTypes = nil
	file_pathInfo_proto_depIdxs = nil
}
