// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: playerInfo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 프리팹 타입 정의 (딱 2가지 타입)
type PrefabType int32

const (
	PrefabType_TYPE_UNDEFINED PrefabType = 0 // 기본값 (정의되지 않은 경우)
	PrefabType_TYPE_A         PrefabType = 1 // 첫 번째 프리팹 타입
	PrefabType_TYPE_B         PrefabType = 2 // 두 번째 프리팹 타입
)

// Enum value maps for PrefabType.
var (
	PrefabType_name = map[int32]string{
		0: "TYPE_UNDEFINED",
		1: "TYPE_A",
		2: "TYPE_B",
	}
	PrefabType_value = map[string]int32{
		"TYPE_UNDEFINED": 0,
		"TYPE_A":         1,
		"TYPE_B":         2,
	}
)

func (x PrefabType) Enum() *PrefabType {
	p := new(PrefabType)
	*p = x
	return p
}

func (x PrefabType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrefabType) Descriptor() protoreflect.EnumDescriptor {
	return file_playerInfo_proto_enumTypes[0].Descriptor()
}

func (PrefabType) Type() protoreflect.EnumType {
	return &file_playerInfo_proto_enumTypes[0]
}

func (x PrefabType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrefabType.Descriptor instead.
func (PrefabType) EnumDescriptor() ([]byte, []int) {
	return file_playerInfo_proto_rawDescGZIP(), []int{0}
}

// 요청, 응답으로 사용할 플레이어의 정보
type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string  `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"` // 플레이어의 고유 ID
	X        float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`             // X 좌표
	Y        float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`             // Y 좌표
	Z        float32 `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`             // Z 좌표
	Rx       float32 `protobuf:"fixed32,5,opt,name=rx,proto3" json:"rx,omitempty"`           // X 축 회전
	Ry       float32 `protobuf:"fixed32,6,opt,name=ry,proto3" json:"ry,omitempty"`           // Y 축 회전
	Rz       float32 `protobuf:"fixed32,7,opt,name=rz,proto3" json:"rz,omitempty"`           // Z 축 회전
	Speed    float32 `protobuf:"fixed32,8,opt,name=speed,proto3" json:"speed,omitempty"`     // 플레이어 속도
	Health   float32 `protobuf:"fixed32,9,opt,name=health,proto3" json:"health,omitempty"`   // 플레이어 체력
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_playerInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_playerInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_playerInfo_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerInfo) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerInfo) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerInfo) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerInfo) GetRx() float32 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *PlayerInfo) GetRy() float32 {
	if x != nil {
		return x.Ry
	}
	return 0
}

func (x *PlayerInfo) GetRz() float32 {
	if x != nil {
		return x.Rz
	}
	return 0
}

func (x *PlayerInfo) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PlayerInfo) GetHealth() float32 {
	if x != nil {
		return x.Health
	}
	return 0
}

var File_playerInfo_proto protoreflect.FileDescriptor

var file_playerInfo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xb0,
	0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x7a, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x02, 0x72, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x02, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x7a, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x02, 0x72, 0x7a, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x2a, 0x38, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x66, 0x61, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x10, 0x02, 0x42, 0x12, 0x5a, 0x10, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_playerInfo_proto_rawDescOnce sync.Once
	file_playerInfo_proto_rawDescData = file_playerInfo_proto_rawDesc
)

func file_playerInfo_proto_rawDescGZIP() []byte {
	file_playerInfo_proto_rawDescOnce.Do(func() {
		file_playerInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_playerInfo_proto_rawDescData)
	})
	return file_playerInfo_proto_rawDescData
}

var file_playerInfo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_playerInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_playerInfo_proto_goTypes = []any{
	(PrefabType)(0),    // 0: playerInfo.PrefabType
	(*PlayerInfo)(nil), // 1: playerInfo.PlayerInfo
}
var file_playerInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_playerInfo_proto_init() }
func file_playerInfo_proto_init() {
	if File_playerInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_playerInfo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playerInfo_proto_goTypes,
		DependencyIndexes: file_playerInfo_proto_depIdxs,
		EnumInfos:         file_playerInfo_proto_enumTypes,
		MessageInfos:      file_playerInfo_proto_msgTypes,
	}.Build()
	File_playerInfo_proto = out.File
	file_playerInfo_proto_rawDesc = nil
	file_playerInfo_proto_goTypes = nil
	file_playerInfo_proto_depIdxs = nil
}
