// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: playerInfo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 플레이어 모델 프리팹 타입 정의 (딱 2가지 타입)
type PlayerModelType int32

const (
	PlayerModelType_MODEL_UNDEFINED PlayerModelType = 0 // 기본값 (정의되지 않은 경우)
	PlayerModelType_MALE            PlayerModelType = 1 // 남캐 프리팹 타입
	PlayerModelType_FEMALE          PlayerModelType = 2 // 여캐 프리팹 타입
)

// Enum value maps for PlayerModelType.
var (
	PlayerModelType_name = map[int32]string{
		0: "MODEL_UNDEFINED",
		1: "MALE",
		2: "FEMALE",
	}
	PlayerModelType_value = map[string]int32{
		"MODEL_UNDEFINED": 0,
		"MALE":            1,
		"FEMALE":          2,
	}
)

func (x PlayerModelType) Enum() *PlayerModelType {
	p := new(PlayerModelType)
	*p = x
	return p
}

func (x PlayerModelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerModelType) Descriptor() protoreflect.EnumDescriptor {
	return file_playerInfo_proto_enumTypes[0].Descriptor()
}

func (PlayerModelType) Type() protoreflect.EnumType {
	return &file_playerInfo_proto_enumTypes[0]
}

func (x PlayerModelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerModelType.Descriptor instead.
func (PlayerModelType) EnumDescriptor() ([]byte, []int) {
	return file_playerInfo_proto_rawDescGZIP(), []int{0}
}

// 플레이어 무기 프리팹 타입 정의
type PlayerWeaponType int32

const (
	PlayerWeaponType_WEAPON_UNDEFINED PlayerWeaponType = 0 // 기본값
	PlayerWeaponType_PISTOL           PlayerWeaponType = 1 // 권총
	PlayerWeaponType_ASSAULT          PlayerWeaponType = 2 // 자동소총
	PlayerWeaponType_SNIPER           PlayerWeaponType = 3 // 저격소총
	PlayerWeaponType_SHOTGUN          PlayerWeaponType = 4 // 샷건
)

// Enum value maps for PlayerWeaponType.
var (
	PlayerWeaponType_name = map[int32]string{
		0: "WEAPON_UNDEFINED",
		1: "PISTOL",
		2: "ASSAULT",
		3: "SNIPER",
		4: "SHOTGUN",
	}
	PlayerWeaponType_value = map[string]int32{
		"WEAPON_UNDEFINED": 0,
		"PISTOL":           1,
		"ASSAULT":          2,
		"SNIPER":           3,
		"SHOTGUN":          4,
	}
)

func (x PlayerWeaponType) Enum() *PlayerWeaponType {
	p := new(PlayerWeaponType)
	*p = x
	return p
}

func (x PlayerWeaponType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerWeaponType) Descriptor() protoreflect.EnumDescriptor {
	return file_playerInfo_proto_enumTypes[1].Descriptor()
}

func (PlayerWeaponType) Type() protoreflect.EnumType {
	return &file_playerInfo_proto_enumTypes[1]
}

func (x PlayerWeaponType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerWeaponType.Descriptor instead.
func (PlayerWeaponType) EnumDescriptor() ([]byte, []int) {
	return file_playerInfo_proto_rawDescGZIP(), []int{1}
}

// 플레이어 애니메이션 파라미터 정의
type AnimationParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsRunning  float32 `protobuf:"fixed32,1,opt,name=isRunning,proto3" json:"isRunning,omitempty"`
	IsAim      bool    `protobuf:"varint,2,opt,name=isAim,proto3" json:"isAim,omitempty"`
	MovementX  float32 `protobuf:"fixed32,3,opt,name=movementX,proto3" json:"movementX,omitempty"`
	MovementY  float32 `protobuf:"fixed32,4,opt,name=movementY,proto3" json:"movementY,omitempty"`
	WeaponType int32   `protobuf:"varint,5,opt,name=weaponType,proto3" json:"weaponType,omitempty"`
}

func (x *AnimationParameters) Reset() {
	*x = AnimationParameters{}
	mi := &file_playerInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimationParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimationParameters) ProtoMessage() {}

func (x *AnimationParameters) ProtoReflect() protoreflect.Message {
	mi := &file_playerInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimationParameters.ProtoReflect.Descriptor instead.
func (*AnimationParameters) Descriptor() ([]byte, []int) {
	return file_playerInfo_proto_rawDescGZIP(), []int{0}
}

func (x *AnimationParameters) GetIsRunning() float32 {
	if x != nil {
		return x.IsRunning
	}
	return 0
}

func (x *AnimationParameters) GetIsAim() bool {
	if x != nil {
		return x.IsAim
	}
	return false
}

func (x *AnimationParameters) GetMovementX() float32 {
	if x != nil {
		return x.MovementX
	}
	return 0
}

func (x *AnimationParameters) GetMovementY() float32 {
	if x != nil {
		return x.MovementY
	}
	return 0
}

func (x *AnimationParameters) GetWeaponType() int32 {
	if x != nil {
		return x.WeaponType
	}
	return 0
}

// 요청, 응답으로 사용할 플레이어의 정보
type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId         string               `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`                                                    // 플레이어의 고유 ID
	X                float32              `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`                                                                // X 좌표
	Y                float32              `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`                                                                // Y 좌표
	Z                float32              `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`                                                                // Z 좌표
	Rx               float32              `protobuf:"fixed32,5,opt,name=rx,proto3" json:"rx,omitempty"`                                                              // X 축 회전
	Ry               float32              `protobuf:"fixed32,6,opt,name=ry,proto3" json:"ry,omitempty"`                                                              // Y 축 회전
	Rz               float32              `protobuf:"fixed32,7,opt,name=rz,proto3" json:"rz,omitempty"`                                                              // Z 축 회전
	Speed            float32              `protobuf:"fixed32,8,opt,name=speed,proto3" json:"speed,omitempty"`                                                        // 플레이어 속도
	Hp               float32              `protobuf:"fixed32,9,opt,name=hp,proto3" json:"hp,omitempty"`                                                              // 플레이어 체력
	RotationSpeed    float32              `protobuf:"fixed32,10,opt,name=rotationSpeed,proto3" json:"rotationSpeed,omitempty"`                                       // 플레이어 회전속도
	PrefabModelType  PlayerModelType      `protobuf:"varint,11,opt,name=prefabModelType,proto3,enum=playerInfo.PlayerModelType" json:"prefabModelType,omitempty"`    // 플레이어의 프리팹 타입
	PrefabWeaponType PlayerWeaponType     `protobuf:"varint,12,opt,name=prefabWeaponType,proto3,enum=playerInfo.PlayerWeaponType" json:"prefabWeaponType,omitempty"` // 무기 프리팹 타입
	AnimParams       *AnimationParameters `protobuf:"bytes,13,opt,name=animParams,proto3" json:"animParams,omitempty"`                                               // 애니메이션 파라미터들
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_playerInfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_playerInfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_playerInfo_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerInfo) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerInfo) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerInfo) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerInfo) GetRx() float32 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *PlayerInfo) GetRy() float32 {
	if x != nil {
		return x.Ry
	}
	return 0
}

func (x *PlayerInfo) GetRz() float32 {
	if x != nil {
		return x.Rz
	}
	return 0
}

func (x *PlayerInfo) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PlayerInfo) GetHp() float32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *PlayerInfo) GetRotationSpeed() float32 {
	if x != nil {
		return x.RotationSpeed
	}
	return 0
}

func (x *PlayerInfo) GetPrefabModelType() PlayerModelType {
	if x != nil {
		return x.PrefabModelType
	}
	return PlayerModelType_MODEL_UNDEFINED
}

func (x *PlayerInfo) GetPrefabWeaponType() PlayerWeaponType {
	if x != nil {
		return x.PrefabWeaponType
	}
	return PlayerWeaponType_WEAPON_UNDEFINED
}

func (x *PlayerInfo) GetAnimParams() *AnimationParameters {
	if x != nil {
		return x.AnimParams
	}
	return nil
}

var File_playerInfo_proto protoreflect.FileDescriptor

var file_playerInfo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xa5,
	0x01, 0x0a, 0x13, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x52, 0x75, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x69, 0x73, 0x52, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x41, 0x69, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x41, 0x69, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f,
	0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x58, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6d,
	0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x58, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x76, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x59, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6d, 0x6f, 0x76,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x59, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x77, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0xa0, 0x03, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a,
	0x01, 0x7a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x0e, 0x0a, 0x02, 0x72,
	0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x72, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x72,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x72,
	0x7a, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x72, 0x7a, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x70, 0x65, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x68,
	0x70, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x70, 0x65,
	0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x45, 0x0a, 0x0f, 0x70, 0x72, 0x65, 0x66, 0x61,
	0x62, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1b, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0f, 0x70,
	0x72, 0x65, 0x66, 0x61, 0x62, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x48,
	0x0a, 0x10, 0x70, 0x72, 0x65, 0x66, 0x61, 0x62, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x57, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x10, 0x70, 0x72, 0x65, 0x66, 0x61, 0x62, 0x57, 0x65,
	0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x61, 0x6e, 0x69, 0x6d,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0a, 0x61,
	0x6e, 0x69, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2a, 0x3c, 0x0a, 0x0f, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f,
	0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46,
	0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x02, 0x2a, 0x5a, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x57,
	0x45, 0x41, 0x50, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x49, 0x53, 0x54, 0x4f, 0x4c, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x41, 0x53, 0x53, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x4e,
	0x49, 0x50, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x48, 0x4f, 0x54, 0x47, 0x55,
	0x4e, 0x10, 0x04, 0x42, 0x12, 0x5a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x67, 0x6f,
	0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_playerInfo_proto_rawDescOnce sync.Once
	file_playerInfo_proto_rawDescData = file_playerInfo_proto_rawDesc
)

func file_playerInfo_proto_rawDescGZIP() []byte {
	file_playerInfo_proto_rawDescOnce.Do(func() {
		file_playerInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_playerInfo_proto_rawDescData)
	})
	return file_playerInfo_proto_rawDescData
}

var file_playerInfo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_playerInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_playerInfo_proto_goTypes = []any{
	(PlayerModelType)(0),        // 0: playerInfo.PlayerModelType
	(PlayerWeaponType)(0),       // 1: playerInfo.PlayerWeaponType
	(*AnimationParameters)(nil), // 2: playerInfo.AnimationParameters
	(*PlayerInfo)(nil),          // 3: playerInfo.PlayerInfo
}
var file_playerInfo_proto_depIdxs = []int32{
	0, // 0: playerInfo.PlayerInfo.prefabModelType:type_name -> playerInfo.PlayerModelType
	1, // 1: playerInfo.PlayerInfo.prefabWeaponType:type_name -> playerInfo.PlayerWeaponType
	2, // 2: playerInfo.PlayerInfo.animParams:type_name -> playerInfo.AnimationParameters
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_playerInfo_proto_init() }
func file_playerInfo_proto_init() {
	if File_playerInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_playerInfo_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playerInfo_proto_goTypes,
		DependencyIndexes: file_playerInfo_proto_depIdxs,
		EnumInfos:         file_playerInfo_proto_enumTypes,
		MessageInfos:      file_playerInfo_proto_msgTypes,
	}.Build()
	File_playerInfo_proto = out.File
	file_playerInfo_proto_rawDesc = nil
	file_playerInfo_proto_goTypes = nil
	file_playerInfo_proto_depIdxs = nil
}
