// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: roomInfo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 룸 정보 메시지
type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId  string        `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`   // 룸 ID. 참여하는 playerId들이 붙어있음
	Players []*PlayerInfo `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"` // 다수의 플레이어 정보를 위한 리스트
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_roomInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_roomInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_roomInfo_proto_rawDescGZIP(), []int{0}
}

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

// 특정 플레이어 정보와 룸 ID를 함께 보내는 요청
type RoomPlayerUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     string      `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`         // 룸 ID
	PlayerInfo *PlayerInfo `protobuf:"bytes,2,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"` // 개별 플레이어 정보
}

func (x *RoomPlayerUpdate) Reset() {
	*x = RoomPlayerUpdate{}
	mi := &file_roomInfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomPlayerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayerUpdate) ProtoMessage() {}

func (x *RoomPlayerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_roomInfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayerUpdate.ProtoReflect.Descriptor instead.
func (*RoomPlayerUpdate) Descriptor() ([]byte, []int) {
	return file_roomInfo_proto_rawDescGZIP(), []int{1}
}

func (x *RoomPlayerUpdate) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomPlayerUpdate) GetPlayerInfo() *PlayerInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

var File_roomInfo_proto protoreflect.FileDescriptor

var file_roomInfo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x10, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x08,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x30, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x22, 0x62, 0x0a, 0x10, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x36,
	0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x12, 0x5a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_roomInfo_proto_rawDescOnce sync.Once
	file_roomInfo_proto_rawDescData = file_roomInfo_proto_rawDesc
)

func file_roomInfo_proto_rawDescGZIP() []byte {
	file_roomInfo_proto_rawDescOnce.Do(func() {
		file_roomInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_roomInfo_proto_rawDescData)
	})
	return file_roomInfo_proto_rawDescData
}

var file_roomInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_roomInfo_proto_goTypes = []any{
	(*RoomInfo)(nil),         // 0: roomInfo.RoomInfo
	(*RoomPlayerUpdate)(nil), // 1: roomInfo.RoomPlayerUpdate
	(*PlayerInfo)(nil),       // 2: playerInfo.PlayerInfo
}
var file_roomInfo_proto_depIdxs = []int32{
	2, // 0: roomInfo.RoomInfo.players:type_name -> playerInfo.PlayerInfo
	2, // 1: roomInfo.RoomPlayerUpdate.playerInfo:type_name -> playerInfo.PlayerInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_roomInfo_proto_init() }
func file_roomInfo_proto_init() {
	if File_roomInfo_proto != nil {
		return
	}
	file_playerInfo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_roomInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_roomInfo_proto_goTypes,
		DependencyIndexes: file_roomInfo_proto_depIdxs,
		MessageInfos:      file_roomInfo_proto_msgTypes,
	}.Build()
	File_roomInfo_proto = out.File
	file_roomInfo_proto_rawDesc = nil
	file_roomInfo_proto_goTypes = nil
	file_roomInfo_proto_depIdxs = nil
}
